#!/usr/bin/with-contenv bash

files=(/etc/nginx/conf.d/*.conf)
if [ ${#files[@]} -eq 0 ]; then
    echo "You must link your nginx conf using this with the docker run command:"
    echo "docker run ...  -v /yourapp/config/app.conf:/etc/nginx/conf.d/app.conf ..."
    exit 1
fi

mkdir -p /tmp/nginx
chown root /tmp/nginx
exec nginx

